/:
  controller: HomeController
  action: index

/register:
  controller: AuthController
  action: register

/login:
  controller: AuthController
  action: login

/forgot-password:
  controller: AuthController
  action: forgotPassword

/reset-password:
  controller: AuthController
  action: resetPassword

/activate:
  controller: AuthController
  action: activate
